name: Auto-merge Dependabot
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
